apply plugin: "java"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

sourceSets {
    
    main {
        java {
            srcDir 'src'
        }
        resources {
            srcDir 'resources'
        }
    }
    test {
        java {
            srcDir 'test'
        }
    }
}

dependencies {
    implementation 'com.microsoft.sqlserver:mssql-jdbc:7.0.0.jre8'

    // test
    testImplementation 'junit:junit:4.13.2'
}