plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
}

java {
    sourceCompatibility JavaVersion.VERSION_21
    targetCompatibility JavaVersion.VERSION_21
}

dependencies {

    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'commons-codec:commons-codec:1.15'
    implementation 'org.jsoup:jsoup:1.13.1'

    // test
    testImplementation 'junit:junit:4.13.2'
}